import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import Providers from "./component/Providers";
import Menu from "./component/Header";
import { Toaster } from "@/components/ui/toaster";
import TawkMessenger from "./component/TawkMesseger";
import Script from "next/script";
import { LanguageProvider } from "./component/LanguageContext";
import { ThemeProvider } from "./Profile/(Home)/Header";
  

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GiPuDiHi Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={roboto.className}>
      <body>
        <ThemeProvider>
          <LanguageProvider>
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            <Providers>
              <div className="min-h-screen bg-base-100 text-base-content">
                {/* <Menu /> */}
                {children}
              </div>
            </Providers>
          </LanguageProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
