// import type { Metadata } from "next";
// // import localFont from "next/font/local";
// import "./globals.css";
// import {
//   ClerkProvider,
//   // SignInButton,
//   // SignedIn,
//   // SignedOut,
//   // UserButton,
// } from "@clerk/nextjs";
// import Header from "./Profile/(Home)/Header";
// import { extractRouterConfig } from "uploadthing/server";
// import { ourFileRouter } from "./api/uploadthing/core";
// import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
// import { Toaster } from "@/components/ui/toaster";
// import { Providers } from "./providers";

// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// export const metadata: Metadata = {
//   title: "GiPuDiHi Shop",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     // <html lang="en">
//     //   <body
//     //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//     //   >
//     //     {children}
//     //   </body>
//     // </html>

//     <html lang="en" suppressHydrationWarning>
//       <body>
//         {/* <Header /> */}
//         <NextSSRPlugin
//           /**
//            * The `extractRouterConfig` will extract **only** the route configs
//            * from the router to prevent additional information from being
//            * leaked to the client. The data passed to the client is the same
//            * as if you were to fetch `/api/uploadthing` directly.
//            */
//           routerConfig={extractRouterConfig(ourFileRouter)}
//         />
//         <Providers>
//           {children}
//           <Toaster />
//         </Providers>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import {Roboto} from 'next/font/google'
import "./globals.css";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { Toaster } from "@/components/ui/toaster";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "GiPuDiHi Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={roboto.className}>
      <body>
        <NextSSRPlugin
          //           /**
          //            * The `extractRouterConfig` will extract **only** the route configs
          //            * from the router to prevent additional information from being
          //            * leaked to the client. The data passed to the client is the same
          //            * as if you were to fetch `/api/uploadthing` directly.
          //            */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
